### ISSUE TITLE
Package breaks Mac OS keyboard word highlighting. 

### ISSUE THREAD

**Issue by ghost** [heilhead/es-identifier-highlight#11]
Default Mac OS behavior is that <kbd>option</kbd><kbd>arrow-key</kbd> will move the cursor by words rather than characters, and that adding <kbd>shift</kbd> will highlight by words rather than characters. 

The latter behavior is broken (cursor movement is cancelled) by this package. Thank you.

**Comment by heilhead** [comment]
Atom allows you to rebind any keybinding you're not happy with.

Go to `Packages` -> `Settings View` -> `Show Keybindings` and click on `your keymap file`. Add following lines and customize them how you want:

``` cson
'atom-text-editor':
  'alt-r alt-r': 'es-identifier-highlight:renameIdentifier'
  'shift-alt-left': 'es-identifier-highlight:prevIdentifier'
  'shift-alt-right': 'es-identifier-highlight:nextIdentifier'
  'shift-alt-up': 'es-identifier-highlight:jumpToDefinition'
```
