### ISSUE TITLE
Refactoring

### ISSUE THREAD

**Issue by brettz9** [heilhead/es-identifier-highlight#5]
Hi,

Since it is kind of in the ballpark of what your very cool plug-in does, I figure I could at least ask to see whether you might be able to add (whether in this plug-in in a new one) the ability to use a key command after highlighting an identifier which would enable one to rename the identifier and simultaneously rename all other instances of that identifier (in scope).

(In Netbeans, one can do this and it will show the other instances changing as you are typing though you would hit "return" to lock in the changes.)

This is an extremely handy feature to use and of course without the risks of find-and-replace due to the scope awareness.

**Comment by heilhead** [comment]
Hi!

Thanks for the feedback. The feature you've described is definitely on my list along with hotkeys to jump between instances of an identifier, but I don't have much time to develop this plugin atm, so it may be somewhere closer to holidays (no promises though).

**Comment by brettz9** [comment]
Cool, thanks---FYI, it looks like someone else is in an alpha stage on this at https://github.com/saitodisse/atom-javascript-refactor

**Comment by brettz9** [comment]
For some reason, I'm not able to get it working, either with the built-in key commands or mapping to my own--any ideas?
