### ISSUE TITLE
Dont't working if spread operator is used

### ISSUE THREAD

**Issue by ya-kostik** [heilhead/es-identifier-highlight#9]
I dont't know why, but when I use spread operator in file plugin doesn't work.

``` javascript
const a = {...object};
```

![2016-04-20 16 32 35](https://cloud.githubusercontent.com/assets/12064332/14676315/011358b8-071e-11e6-9a45-11958bf77dcc.png)
![2016-04-20 16 32 50](https://cloud.githubusercontent.com/assets/12064332/14676319/067bc448-071e-11e6-9621-872bcb56c3b0.png)

Regards.

**Comment by heilhead** [comment]
I'm not quite sure this syntax is valid. Are you trying to create an object from another object or an array? Anyway, the [underlying AST parser](https://github.com/ternjs/acorn) is unable to make sense of this code. If it's a bug in older version then I should probably update it, but looks to me like the syntax is invalid.

**Comment by ya-kostik** [comment]
The syntax is valid. I just take fields from one object and push it to another. If you're interested, there is [an article on MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_operator).

My example is a part of the working project.

I think Acorn [understands it](https://github.com/ternjs/acorn/search?utf8=✓&q=SpreadElement&type=Code), but still not fully.

Thanks.

**Comment by ya-kostik** [comment]
I know why that is happened. Spread operator for objects is not a ES6. It's ES7. I think, when it will be on stable stage, Acorn will understands it too.
